version: "3.9"
services:
  mte-relay:
    image: "aws-mte-relay-server-test:latest"
    ports:
      - 8085:8080
    environment:
      - UPSTREAM=https://jsonplaceholder.typicode.com
      - CLIENT_ID_SECRET=superSecretStringHere
      - CORS_ORIGINS=http://localhost:4200
